# YAML linting configuration for AI Backend configs
extends: default

rules:
  line-length:
    max: 120
    level: warning

  indentation:
    spaces: 2
    indent-sequences: true

  comments:
    min-spaces-from-content: 1

  document-start: disable  # Don't require --- at start

  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
