#!/bin/bash
# Check that generated config files haven't been manually edited
# Used by pre-commit hook
#
# This script enforces that config/litellm-unified.yaml is AUTO-GENERATED
# and detects manual edits by checking for the generation marker.

set -e

CONFIG_FILE="config/litellm-unified.yaml"
VERSION_FILE="config/.litellm-version"

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check if file exists
if [ ! -f "$CONFIG_FILE" ]; then
    echo -e "${GREEN}✅ Config file doesn't exist yet (ok for initial setup)${NC}"
    exit 0
fi

# Check if this is a git commit (skip check for emergency override)
if [ -n "$SKIP_AUTOGEN_CHECK" ]; then
    echo -e "${YELLOW}⚠️  SKIPPING AUTO-GENERATED CHECK (SKIP_AUTOGEN_CHECK set)${NC}"
    exit 0
fi

# Check for proper AUTO-GENERATED header marker
if ! grep -q "^# AUTO-GENERATED FILE - DO NOT EDIT MANUALLY" "$CONFIG_FILE"; then
    echo -e "${RED}❌ BLOCKED: config/litellm-unified.yaml is missing AUTO-GENERATED marker${NC}"
    echo ""
    echo "This file must be generated using scripts/generate-litellm-config.py"
    echo ""
    echo "To fix:"
    echo "  1. Discard manual changes to config/litellm-unified.yaml"
    echo "  2. Edit source files: config/providers.yaml or config/model-mappings.yaml"
    echo "  3. Regenerate: python3 scripts/generate-litellm-config.py"
    echo ""
    echo "EMERGENCY OVERRIDE (use with caution):"
    echo "  SKIP_AUTOGEN_CHECK=1 git commit ..."
    echo ""
    exit 1
fi

# Check that the generated-by marker is present
if ! grep -q "^# Generated by: scripts/generate-litellm-config.py" "$CONFIG_FILE"; then
    echo -e "${RED}❌ BLOCKED: config/litellm-unified.yaml has invalid generation marker${NC}"
    echo ""
    echo "File appears to be manually modified. Expected marker:"
    echo "  # Generated by: scripts/generate-litellm-config.py"
    echo ""
    echo "To fix: Regenerate with python3 scripts/generate-litellm-config.py"
    exit 1
fi

# Verify version file exists and matches
if [ -f "$VERSION_FILE" ]; then
    VERSION_IN_FILE=$(grep "^# Version:" "$CONFIG_FILE" | awk '{print $3}')
    VERSION_IN_TRACKER=$(grep "^version:" "$VERSION_FILE" | awk '{print $2}')

    if [ -n "$VERSION_IN_FILE" ] && [ -n "$VERSION_IN_TRACKER" ]; then
        if [ "$VERSION_IN_FILE" != "$VERSION_IN_TRACKER" ]; then
            echo -e "${YELLOW}⚠️  Warning: Version mismatch detected${NC}"
            echo "  Config file version: $VERSION_IN_FILE"
            echo "  Tracker version: $VERSION_IN_TRACKER"
            echo ""
            echo "Consider regenerating: python3 scripts/generate-litellm-config.py"
        fi
    fi
fi

# Check if source files are newer than generated config
CONFIG_MTIME=$(stat -c %Y "$CONFIG_FILE" 2>/dev/null || stat -f %m "$CONFIG_FILE" 2>/dev/null || echo 0)
PROVIDERS_MTIME=$(stat -c %Y config/providers.yaml 2>/dev/null || stat -f %m config/providers.yaml 2>/dev/null || echo 0)
MAPPINGS_MTIME=$(stat -c %Y config/model-mappings.yaml 2>/dev/null || stat -f %m config/model-mappings.yaml 2>/dev/null || echo 0)

if [ "$PROVIDERS_MTIME" -gt "$CONFIG_MTIME" ] || [ "$MAPPINGS_MTIME" -gt "$CONFIG_MTIME" ]; then
    echo -e "${YELLOW}⚠️  Warning: Source files are newer than generated config${NC}"
    echo "  Regenerate with: python3 scripts/generate-litellm-config.py"
    echo ""
fi

echo -e "${GREEN}✅ Config file has valid AUTO-GENERATED marker${NC}"
exit 0
